apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: staging
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAJpPAeBjAGtr9IPoNhCtB7rZmvUmgY675H+ZogNpDcyEx+NexjeoT0HAD4/gPdBQZUGeYOoMen2EhK2fDYHfXynPaDSRjd4U0KGC7sjzRl/NzavMXfhUhtu7AgXtFXXR3Ep1ZDYdODHV7QTvI165DqnWalJbZ9bkHMU9JZGc/SSzuFOV3pgkSRoUULwjVzCPHM5yiR7VsPa85jZhQ8SLO5t6UiE9HJ4DON7oKlLCYC0Jqtazr0cPPvC9ALvuvlpd1sFynQnbZaKrxYd2kmILCsYHLE3FiYA8NJkArTtq5NRh37BWUuTaNwMxC5xANN5g0mDKdJaHjcTwd7iwNWe5b5G0tTis9RyTHYhF/mVv2ApO3DFCUmM2xcJi7zzECmf88BN+3bYU7Z6MSiJJoVjZz4+OMls+ANpR+k9zIx4R6sg8fz5TieslMHoS1bCrzX3XeBwvYDKLyDUT4IGlUlOV9mzoqGYwv/RclN9QS1/KWa+6wDWYeBg8DfQLIIXnTuD+DT2wuvd6J5ZodA86C7uZdZDDY+L9OoeDdhutijsq+/ltDwvm5WWfIE46yN/Os9ySNXoQvP8V4N2vg1HuhgXp9g0oawi9rilCVz3k3dfHMSnpVyaGkU4IudotWbuyHdiqpIr+lE+PbTRK9NltQ/91+YdUzoF8XYm5qB1ayQJfcArFT3NUjqzIbGeuEzTpTPkho4B6mvGyvT3hALwUS9Ey+rLRf5A22eMwjN1qhqymPJek1X37KVoGmhcdbl
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: staging
    type: Opaque

