apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong 
  template:
    metadata:
      labels:
        app: pingpong 
    spec:
      containers:
        - name: pingpong
          image: tfhuhtal/pingpong:1.11
          volumeMounts:
            - name: logoutput-volume 
              mountPath: /usr/src/app/files
      volumes:
        - name: logoutput-volume
          persistentVolumeClaim:
            claimName: image-claim
