{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "postgres-secret",
    "namespace": "exercises",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "postgres-secret",
        "namespace": "exercises",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "POSTGRES_PASSWORD": "AgBiiH+MEE2rEA0Fxobpm4Jr0VvbH7mikbfW05b8DIa1SSpM8ViaZLrIpAbqi7Y1BpsL7fvM2iXoMon6Xyl4mrvXlzKo5zUVK4cGaodWG6SUGj4GHfVelSwNvFFchsdvGy6qWo9BhetN3eRLP0/yvmSJFtvHqMfheRKjKwfyknmSBHCRE3j6sdMNIFiCub14F42ncwIJWJelm6sasf1Uf2CZ1O13Ej+fXFU/Oo3Lv4P/gIDvq/o4q+rQjq3y0y2qUF6gllQu+++76irae3YpvOE94SKk+epzd71GCr89JAB5nQ0aOkXvwoNTcVb49LlOjv69EMA1TWebxhcdBLRR6us5owrSlyENSDKYOSSMrO+G0yIB+pdupJiq7CfowkjPTf1q8enLp2I7ih7rFVJPpnYtoffH6fG+ibwQLNuI+mLtDhUs/jEL8NeaK/PqtRfa5Enqb1uDxCvUUSU3JMRHfPBLMkEEmLfC7HmmSd6EHXyg+elJ0TDsVjUhUcjPseX7vQoIKlLHcz1zgAFK/whDDWxj/8+qkPHM1Z5NBWa7uW1ql8Wn8gM1os5MJSKC7UiYRUceFKub/GuO1mG8Pmjk6rvgckn9UC0+NbuCQJATtdg75nU8Dv2eeHhvbZNa6VXgJxsHeRr+OkfCRAW0AdRGwR7kyCVxjiB3TovBYkV0zEK79x75jyWwUAPbHlUSGLJ4LBlHcpLa/64yYg=="
    }
  }
}
