apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- ../../base/todo-backend
- ../../base/todo-publisher
- ../../base/todo-app
- ./todo-publisher/sealedsecret.yaml
- ./todo-backend/sealedsecret.yaml

images:
- name: BACKEND_IMAGE
  newName: tfhuhtal/todo-backend
  newTag: 9b3400a87624a377a02086dcb81c8a3f8d22d1db
- name: CRONJOB_IMAGE
  newName: tfhuhtal/todo-cron
  newTag: 9b3400a87624a377a02086dcb81c8a3f8d22d1db
- name: FRONTEND_IMAGE
  newName: tfhuhtal/todo-app
  newTag: 9b3400a87624a377a02086dcb81c8a3f8d22d1db
- name: PUBLISHER_IMAGE
  newName: tfhuhtal/todo-publisher
  newTag: 9b3400a87624a377a02086dcb81c8a3f8d22d1db
