apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- ../../base/todo-backend
- ../../base/todo-publisher
- ../../base/todo-app
- ./todo-publisher/sealedsecret.yaml
- ./todo-backend/sealedsecret.yaml

images:
- name: BACKEND_IMAGE
  newName: tfhuhtal/todo-backend
  newTag: 9803a70ed9c19c72995b9c541dc5419082087f26
- name: CRONJOB_IMAGE
  newName: tfhuhtal/todo-cron
  newTag: 9803a70ed9c19c72995b9c541dc5419082087f26
- name: FRONTEND_IMAGE
  newName: tfhuhtal/todo-app
  newTag: 9803a70ed9c19c72995b9c541dc5419082087f26
- name: PUBLISHER_IMAGE
  newName: tfhuhtal/todo-publisher
  newTag: 9803a70ed9c19c72995b9c541dc5419082087f26
