apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- ../../base/todo-backend
- ../../base/todo-publisher
- ../../base/todo-app
- todo-publisher/sealedsecret.yaml
- todo-backend/sealedsecret.yaml

images:
- name: BACKEND_IMAGE
  newName: tfhuhtal/todo-backend
  newTag: 088c2ff028ace34ce5dab5838af1f6e9c993b81b
- name: CRONJOB_IMAGE
  newName: tfhuhtal/todo-cron
  newTag: 088c2ff028ace34ce5dab5838af1f6e9c993b81b
- name: FRONTEND_IMAGE
  newName: tfhuhtal/todo-app
  newTag: 088c2ff028ace34ce5dab5838af1f6e9c993b81b
- name: PUBLISHER_IMAGE
  newName: tfhuhtal/todo-publisher
  newTag: 088c2ff028ace34ce5dab5838af1f6e9c993b81b
