apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
  - ../../base/todo-backend
  - ../../base/todo-publisher
  - ../../base/todo-app
  - todo-publisher/sealedsecret.yaml
  - todo-backend/sealedsecret.yaml

images:
  - name: FRONTEND_IMAGE
    newName: tfhuhtal/todo-app:v1.9
  - name: BACKEND_IMAGE
    newName: tfhuhtal/todo-backend:v2.0
  - name: CRONJOB_IMAGE
    newName: tfhuhtal/todo-cron:2.092
  - name: PUBLISHER_IMAGE
    newName: tfhuhtal/todo-publisher:v2.001
