apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- ../../base/todo-backend
- ../../base/todo-publisher
- ../../base/todo-app
- ./todo-publisher/sealedsecret.yaml
- ./todo-backend/sealedsecret.yaml

images:
- name: BACKEND_IMAGE
  newName: tfhuhtal/todo-backend
  newTag: def5834b27a2963d10924070ba230e0633392f49
- name: CRONJOB_IMAGE
  newName: tfhuhtal/todo-cron
  newTag: def5834b27a2963d10924070ba230e0633392f49
- name: FRONTEND_IMAGE
  newName: tfhuhtal/todo-app
  newTag: def5834b27a2963d10924070ba230e0633392f49
- name: PUBLISHER_IMAGE
  newName: tfhuhtal/todo-publisher
  newTag: def5834b27a2963d10924070ba230e0633392f49
