apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- ../../base/todo-backend
- ../../base/todo-publisher
- ../../base/todo-app
- ./todo-publisher/sealedsecret.yaml
- ./todo-backend/sealedsecret.yaml

images:
- name: BACKEND_IMAGE
  newName: tfhuhtal/todo-backend
  newTag: b11009fcb5067804cfcd57a0c5a2c630ea2b597e
- name: CRONJOB_IMAGE
  newName: tfhuhtal/todo-cron
  newTag: b11009fcb5067804cfcd57a0c5a2c630ea2b597e
- name: FRONTEND_IMAGE
  newName: tfhuhtal/todo-app
  newTag: b11009fcb5067804cfcd57a0c5a2c630ea2b597e
- name: PUBLISHER_IMAGE
  newName: tfhuhtal/todo-publisher
  newTag: b11009fcb5067804cfcd57a0c5a2c630ea2b597e
