apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- ../../base/todo-backend
- ../../base/todo-publisher
- ../../base/todo-app
- ./todo-publisher/sealedsecret.yaml
- ./todo-backend/sealedsecret.yaml

images:
- name: BACKEND_IMAGE
  newName: tfhuhtal/todo-backend
  newTag: 0f8c0dcf252d8198706f867823f079131ccfd01a
- name: CRONJOB_IMAGE
  newName: tfhuhtal/todo-cron
  newTag: 0f8c0dcf252d8198706f867823f079131ccfd01a
- name: FRONTEND_IMAGE
  newName: tfhuhtal/todo-app
  newTag: 0f8c0dcf252d8198706f867823f079131ccfd01a
- name: PUBLISHER_IMAGE
  newName: tfhuhtal/todo-publisher
  newTag: 0f8c0dcf252d8198706f867823f079131ccfd01a
