apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- ../../base/todo-backend
- ../../base/todo-publisher
- ../../base/todo-app
- ./todo-publisher/sealedsecret.yaml
- ./todo-backend/sealedsecret.yaml

images:
- name: BACKEND_IMAGE
  newName: tfhuhtal/todo-backend
  newTag: b849476978c306267e8324ebe0ea3a532490656c
- name: CRONJOB_IMAGE
  newName: tfhuhtal/todo-cron
  newTag: b849476978c306267e8324ebe0ea3a532490656c
- name: FRONTEND_IMAGE
  newName: tfhuhtal/todo-app
  newTag: b849476978c306267e8324ebe0ea3a532490656c
- name: PUBLISHER_IMAGE
  newName: tfhuhtal/todo-publisher
  newTag: b849476978c306267e8324ebe0ea3a532490656c
