apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- ../../base/todo-backend
- ../../base/todo-publisher
- ../../base/todo-app
- ./todo-publisher/sealedsecret.yaml
- ./todo-backend/sealedsecret.yaml

images:
- name: BACKEND_IMAGE
  newName: tfhuhtal/todo-backend
  newTag: 5053bcc7ad134fec8c990feef583d8a63007d1c7
- name: CRONJOB_IMAGE
  newName: tfhuhtal/todo-cron
  newTag: 5053bcc7ad134fec8c990feef583d8a63007d1c7
- name: FRONTEND_IMAGE
  newName: tfhuhtal/todo-app
  newTag: 5053bcc7ad134fec8c990feef583d8a63007d1c7
- name: PUBLISHER_IMAGE
  newName: tfhuhtal/todo-publisher
  newTag: 5053bcc7ad134fec8c990feef583d8a63007d1c7
