apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- ../../base/todo-backend
- ../../base/todo-publisher
- ../../base/todo-app
- ./todo-publisher/sealedsecret.yaml
- ./todo-backend/sealedsecret.yaml

images:
- name: BACKEND_IMAGE
  newName: tfhuhtal/todo-backend
  newTag: 41d0afb93049dcc5009edd2982db2be9fb5c1850
- name: CRONJOB_IMAGE
  newName: tfhuhtal/todo-cron
  newTag: 41d0afb93049dcc5009edd2982db2be9fb5c1850
- name: FRONTEND_IMAGE
  newName: tfhuhtal/todo-app
  newTag: 41d0afb93049dcc5009edd2982db2be9fb5c1850
- name: PUBLISHER_IMAGE
  newName: tfhuhtal/todo-publisher
  newTag: 41d0afb93049dcc5009edd2982db2be9fb5c1850
