apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/deployment.yaml
  - manifests/postgres.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml
  - manifests/todocron.yaml
  - manifests/secret.yaml
  - manifests/backupcron.yaml
  - manifests/analysistemplate.yaml
  - manifests/rollout.yaml

images:
  - name: FRONTEND_IMAGE
    newName: tfhuhtal/todo-app:v1.9
  - name: BACKEND_IMAGE
    newName: tfhuhtal/todo-backend:v2.0
  - name: CRONJOB_IMAGE
    newName: tfhuhtal/todo-cron:2.092
  - name: PG_BACKUP_IMAGE
  - name: PUBLISHER_IMAGE
    newName: tfhuhtal/todo-publisher:v2.001
