apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats:latest
        ports:
        - containerPort: 4222
        - containerPort: 6222
        - containerPort: 8222
        args: ["-m", "8222"]
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: project
spec:
  ports:
    - port: 4222
      targetPort: 4222
      protocol: TCP
  selector:
    app: nats
