apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project 
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
        - name: project
          image: FRONTEND_IMAGE
          volumeMounts:
            - name: project-volume
              mountPath: /usr/src/app/files
      volumes:
        - name: project-volume 
          persistentVolumeClaim:
            claimName: project-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: BACKEND_IMAGE
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret 
                  key: POSTGRES_PASSWORD
