apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project-claim # name of ther volume claim, this will be used in the deployment
spec:
  storageClassName: project-pv # this is the name of the persisten volume we are claiming
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
