apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: project-claim # name of ther volume claim, this will be used in the deployment
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
