# https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/
apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-cron 
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: todo-cron
            image: tfhuhtal/todo-cron:2.092
            imagePullPolicy: Always
          restartPolicy: Never
---

