apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/secret.enc.yaml
  - manifests/postgres.yaml

images:
  - name: PINGPONG_IMAGE
    newName: tfhuhtal/pingpong:4.1