apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests/kservice.yaml
- manifests/sealedsecret.yaml
- manifests/postgres.yaml

images:
- name: PINGPONG_IMAGE
  newName: tfhuhtal/pingpong
  newTag: e35641e8ddf8c113c9b4e64a85dd26be608b682d
