apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput 
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: logoutput-volume 
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: logoutput
          image: tfhuhtal/logoutput-finder:2.01
          volumeMounts: 
            - name: logoutput-volume
              mountPath: /usr/src/app/files
        - name: logoutput-hasher
          image: tfhuhtal/logoutput-hasher:1.101
          volumeMounts:
            - name: logoutput-volume
              mountPath: /usr/src/app/files
