apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: exercises
  name: logoutput-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: logoutput-svc
            port:
              number: 2345
      - path: /pingpong 
        pathType: Prefix
        backend:
          service:
            name: pingpong-svc
            port:
              number: 2345

