apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: telegram-secret
  namespace: staging
spec:
  encryptedData:
    TELEGRAM_BOT_TOKEN: AgB+6aMrL1vqy/cWFk7ab+rYsHsbIXikyVMJGMY+fb5wBuwmZGpX9fYbbn8ae8jTcZdXyGlwN/qp35f7pArqpxcMQp8PlTtn3G+hC29Rk6MlR8DKqGz6AtYyaiYTPGtuwZlALZX8yITipbn4L+KrkwDdOF/Alv2grNTjLj1szpeWvltJGPb40WC7QHCzwkMogHjvdpzJeJTQwGzXpeS2nqXBoQw+s3tV8gN4ojbic87UW/2Y/Yxs4/mxP9lpsWwqvGNTDViSGAbzFS8XeG20VwktoEB9WR9yyfOMm74IkTqqZj7OBeEzxNQsVb6BSNNOYuIlwzhqtAXqTVqyTCJNcwdutiuW3O+6NmwhO6Rf6teXwhb/B6NCSjB/a1vVeciWsIk4bFm++AWAy3FNhqEVEcDcaBFmL4sOO99HkCaX9t0RFGbesWKV+f6yteMBj01RnOnkcDsn7kQ6jJQqmaNaQdqNaplgpSYBxRJ7VFtn43Ya0esMUWiQ9b/GHUYKlDC9Xx11w/4mp/YjvQQr79zR3L2dUDdV/JQkyKMsJXwksgYzrmMCaNdsJ2Bs7h8RuTgWRIV2yJank3F2HrazD5Fv3bGk8vMdprLwS/VmjZT0Rp933Ww1gcQrIJPvlv0sGQtRNw9o1nQnRf7DS4oFhzLY3l3qlTSUk6z6FvUbXwG/FklEYYCLFajL2dKfFElmHvVzL1rUWyuyrIO+UtmbkXldWUKZTqoT/LDASzk70hDHNx+O2xtt/aLPqbiR44Om
  template:
    metadata:
      creationTimestamp: null
      name: telegram-secret
      namespace: staging
    type: Opaque

