apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

resources:
- ../../base/todo-backend
- ../../base/todo-publisher
- ../../base/todo-app
- todo-backend/sealedsecret.yaml
- todo-backend/backupcron.yaml
- todo-publisher/sealedsecret.yaml

images:
- name: BACKEND_IMAGE
  newName: tfhuhtal/todo-backend
  newTag: cd4c3403803450f13ae88feabd0641ff09dae008
- name: CRONJOB_IMAGE
  newName: tfhuhtal/todo-cron
  newTag: cd4c3403803450f13ae88feabd0641ff09dae008
- name: FRONTEND_IMAGE
  newName: tfhuhtal/todo-app
  newTag: cd4c3403803450f13ae88feabd0641ff09dae008
- name: PG_BACKUP_IMAGE
  newName: tfhuhtal/backup-db
  newTag: cd4c3403803450f13ae88feabd0641ff09dae008
- name: PUBLISHER_IMAGE
  newName: tfhuhtal/todo-publisher
  newTag: cd4c3403803450f13ae88feabd0641ff09dae008
