name: Clean up
on:
  delete:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  BRANCH: ${{ github.ref_name }}

jobs:
  clean-up:
    name: Clean up 
    runs-on: ubuntu-latest
    environment: sirit
    if: github.event.ref_type == 'branch'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2

      - name: "Use gcloud CLI"
        run: gcloud info

      - run: gcloud --quiet auth configure-docker

      - name: "Get GKE credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "${{ env.GKE_CLUSTER }}"
          project_id: "${{ env.PROJECT_ID }}"
          location: "${{ env.GKE_ZONE }}"

      - name: Extract deleted branch name and set namespace
        run: |
          DELETED_BRANCH=${{ github.event.ref }}
          if [[ "${DELETED_BRANCH}" == "refs/heads/main" ]]; then
            echo "Branch 'main' cannot be deleted." && exit 1
          fi
          NAMESPACE=${DELETED_BRANCH#refs/heads/}
          echo "NAMESPACE=${NAMESPACE}" >> $GITHUB_ENV

      - name: Delete environment
        run: |
          if kubectl get namespace ${NAMESPACE}; then
            kubectl delete namespace ${NAMESPACE}
          else
            echo "Namespace ${NAMESPACE} does not exist, nothing to delete."
          fi
