name: Release project

on:
  push:
    paths:
      - 'project/**'
      - '.github/workflows/main.yaml'

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  BRANCH: ${{ github.ref_name }}

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy 
    runs-on: ubuntu-latest
    environment: sirit

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: "Set up Cloud SDK"
        uses: google-github-actions/setup-gcloud@v2

      - name: "Use gcloud CLI"
        run: gcloud info

      - run: gcloud --quiet auth configure-docker

      - name: "Get GKE credentials"
        uses: "google-github-actions/get-gke-credentials@v2"
        with:
          cluster_name: "${{ env.GKE_CLUSTER }}"
          project_id: "${{ env.PROJECT_ID }}"
          location: "${{ env.GKE_ZONE }}"

      - name: Decrypt secret
        run: |
          curl -LO https://github.com/getsops/sops/releases/download/v3.9.0/sops_3.9.0_amd64.deb
          sudo dpkg -i sops_3.9.0_amd64.deb
          export SOPS_AGE_KEY=${{ secrets.SOPS_AGE_KEY }}
          sops --decrypt project/manifests/secret.enc.yaml > project/manifests/secret.yaml

      - name: Build
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/todo-app:$BRANCH-$GITHUB_SHA" ./project/todo-app
          docker build --tag "gcr.io/$PROJECT_ID/todo-backend:$BRANCH-$GITHUB_SHA" ./project/todo-backend
          docker build --tag "gcr.io/$PROJECT_ID/todo-cron:$BRANCH-$GITHUB_SHA" ./project/cron

      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_ID/todo-app:$BRANCH-$GITHUB_SHA"
          docker push "gcr.io/$PROJECT_ID/todo-backend:$BRANCH-$GITHUB_SHA"
          docker push "gcr.io/$PROJECT_ID/todo-cron:$BRANCH-$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Deploy
        run: |-
          kustomize edit set image FRONTEND_IMAGE=gcr.io/$PROJECT_ID/todo-app:$BRANCH-$GITHUB_SHA
          kustomize edit set image BACKEND_IMAGE=gcr.io/$PROJECT_ID/todo-backend:$BRANCH-$GITHUB_SHA
          kustomize edit set image CRONJOB_IMAGE=gcr.io/$PROJECT_ID/todo-cron:$BRANCH-$GITHUB_SHA
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment $SERVICE
          kubectl get services -o wide
