name: Build and Deploy

on:
  push:
    paths:
      - 'pingpong/**'
      - '.github/workflows/pingpong.yaml'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: sirit

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push the Docker image
        run: |-
          docker build -t tfhuhtal/pingpong:$GITHUB_SHA ./pingpong
          docker push tfhuhtal/pingpong:$GITHUB_SHA

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update image in kustomization.yaml
        run: |-
          cd pingpong
          kustomize edit set image PINGPONG_IMAGE=tfhuhtal/pingpong:$GITHUB_SHA
    
      - name: Commit changes to kustomization.yaml
        uses: EndBug/add-and-commit@v9
        with:
          add: 'pingpong/kustomization.yaml'
          message: New version ${{ github.sha }} released pingpong