name: Build and publish project to production

on:
  push:
    tags:
      - '*'

jobs:
  build-publish:
    name: Build, push and publish to production
    runs-on: ubuntu-latest
    environment: sirit

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Switch to the main branch
        run: |
          git fetch origin main
          git checkout main

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and publish application
        working-directory: project
        run: |-
          docker build --tag tfhuhtal/todo-backend:${GITHUB_SHA} todo-backend
          docker build --tag tfhuhtal/todo-app:${GITHUB_SHA} todo-app
          docker build --tag tfhuhtal/backup-db:${GITHUB_SHA} backup-cron
          docker build --tag tfhuhtal/todo-publisher:${GITHUB_SHA} todo-publisher
          docker build --tag tfhuhtal/todo-cron:${GITHUB_SHA} cron
          docker push tfhuhtal/todo-backend:${GITHUB_SHA}
          docker push tfhuhtal/todo-app:${GITHUB_SHA}
          docker push tfhuhtal/backup-db:${GITHUB_SHA}
          docker push tfhuhtal/todo-publisher:${GITHUB_SHA}
          docker push tfhuhtal/todo-cron:${GITHUB_SHA}

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update images in kustomization.yaml
        working-directory: project/overlays/prod
        run: |-
          kustomize edit set image FRONTEND_IMAGE=tfhuhtal/todo-app:${GITHUB_SHA}
          kustomize edit set image BACKEND_IMAGE=tfhuhtal/todo-backend:${GITHUB_SHA}
          kustomize edit set image PG_BACKUP_IMAGE=tfhuhtal/backup-db:${GITHUB_SHA}
          kustomize edit set image CRONJOB_IMAGE=tfhuhtal/todo-cron:${GITHUB_SHA}
          kustomize edit set image PUBLISHER_IMAGE=tfhuhtal/todo-publisher:${GITHUB_SHA}

      - name: Commit changes to kustomization.yaml
        uses: EndBug/add-and-commit@v9
        with:
          add: 'project/overlays/prod/kustomization.yaml'
          message: New version ${{ env.TAG_NAME }} released to production